// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7XaWcPZGUZeYc3Ki9R7Bp9R5X2tB95Lw',
    appId: '1:1009445090491:web:c46ea366b5d3663edf659e',
    messagingSenderId: '1009445090491',
    projectId: 'hcareapp-ee339',
    authDomain: 'hcareapp-ee339.firebaseapp.com',
    storageBucket: 'hcareapp-ee339.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL35_HXgE8ZaJA4cWsqnLRhc2Pt7a96tg',
    appId: '1:1009445090491:android:25a7a1a8a24caba9df659e',
    messagingSenderId: '1009445090491',
    projectId: 'hcareapp-ee339',
    storageBucket: 'hcareapp-ee339.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC2K_1Z3MdKC6Z5yyOYrGMYzO9r4UO6mY',
    appId: '1:1009445090491:ios:877ab88c20c97467df659e',
    messagingSenderId: '1009445090491',
    projectId: 'hcareapp-ee339',
    storageBucket: 'hcareapp-ee339.appspot.com',
    iosBundleId: 'com.example.hcareapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC2K_1Z3MdKC6Z5yyOYrGMYzO9r4UO6mY',
    appId: '1:1009445090491:ios:ff541d6449a13a31df659e',
    messagingSenderId: '1009445090491',
    projectId: 'hcareapp-ee339',
    storageBucket: 'hcareapp-ee339.appspot.com',
    iosBundleId: 'com.example.hcareapp.RunnerTests',
  );
}
